---
- name: Notify Mattermost Channel
  hosts: localhost
  gather_facts: false

  vars:
    alert_details_value: "{{ snow_incident_link | default('')}}{{ details }}{{ vm_name | default('')}}"

  roles:
    - shadowman_mattermost
