---
- name: Test of play
  hosts: all
  gather_facts: false

  tasks:

  - name: Show all the hosts in the current play
    ansible.builtin.debug:
      msg: "{{ item }} and {{ ansible_loop.index0 }}"
    loop: "{{ new }}"
    vars:
      new: '{{ hostvars|dictsort|selectattr("1.ansible_host", "defined")|map(attribute="1.ansible_host")|list }}'
    delegate_to: localhost
    run_once: true
      