---
- name: Test of play
  hosts: all
  gather_facts: false

  tasks:

  - name: Show all the hosts in the current play
    ansible.builtin.debug:
      msg: "{{ item }} and {{ ansible_loop.index0 }}"
    loop: "{{ ansible_play_batch }}"
    loop_control:
      extended: yes
    delegate_to: localhost
    run_once: true
      