---
- name: Test of play
  hosts: all
  gather_facts: false

  tasks:

  - name: Show all the hosts in the current play
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ new }}"
    vars:
      new: '{{ hostvars|dictsort|selectattr("1.host", "defined")|map(attribute="0")|list }}'
    delegate_to: localhost
    run_once: true
      