---
- name: Update Remediation Job Template
  ansible.controller.job_template:
    name: "Insights Remediation"
    job_type: "run"
    credentials:
      - "Ansible Linux Service Account"
    inventory: "Shadowman Production"
    project: "Red Hat Insights"
    playbook: "{{ item | lower }}-{{ pbs_per_host.results[my_idx | int].content.id }}"
    become_enabled: true
    state: present
    validate_certs: false
  delegate_to: localhost

- name: Launch Remediation Job Template
  ansible.controller.job_launch:
    name: "Insights Remediation"
    wait: true
    validate_certs: false
  delegate_to: localhost

- name: Send notification message via Mattermost of CVE resolved
  community.general.mattermost:
    url: "{{ mattermost_url }}"
    api_key: "{{ mattermost_api_key }}"
    attachments:
      - text: "! ALERT !"
        color: '#ff00dd'
        title: "CVE Issue"
        fields:
          - title: Issue
            value: "CVE Issue Resolved"
            short: true
          - title: Details
            value: "CVE {{ item }} resolved on host {{ insights_adv_target_host }}."
            short: true
  delegate_to: localhost
