---
- name: Get VM info
  vmware.vmware_rest.vcenter_vm_info:
    filter_names:
    - "{{ inventory_hostname }}"
    vcenter_validate_certs: no
  register: vm_info
  delegate_to: localhost

- name: Collect id about a specific VM
  vmware.vmware_rest.vcenter_vm_info:
    vm: "{{ vm_info.value[0].vm }}"
    vcenter_validate_certs: no
  register: vm_full_info
  delegate_to: localhost

- name: Retrieve the CPU information from the VM
  vmware.vmware_rest.vcenter_vm_hardware_cpu_info:
    vm: '{{ vm_full_info.id }}'
    vcenter_validate_certs: no
  register: vm_cpu
  delegate_to: localhost

- name: Add one core to the VM
  vmware.vmware_rest.vcenter_vm_hardware_cpu:
    vm: '{{ vm_full_info.id }}'
    count: '{{ vm_cpu.value.count |int + 1}}'
    vcenter_validate_certs: no
  delegate_to: localhost
