---
- name: Get Host id
  ansible.builtin.uri:
    url: https://{{ lookup('env', 'TOWER_HOST') }}/api/v2/hosts/?name={{ inventory_hostname }}&inventory_id=5
    user: "{{ lookup('env', 'TOWER_USERNAME') }}"
    password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    force_basic_auth: true
    method: "GET"
    status_code: "200"
    validate_certs: no
  register: host_details

- name: Retrieve Job Summaries
  ansible.builtin.uri:
    url: https://{{ lookup('env', 'TOWER_HOST') }}/api/v2/hosts/{{ host_details.json.results[0].id }}/job_host_summaries/?job__job_template_id=581&created__regex={{ ansible_date_time.date }}
    user: "{{ lookup('env', 'TOWER_USERNAME') }}"
    password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    force_basic_auth: true
    method: "GET"
    status_code: "200"
    validate_certs: no
  register: job_details

- name: Counter value
  ansible.builtin.set_fact:
    counter: "{{ job_details | regex_findall('processed') | length }}"

- name: Create Support Ticket
  servicenow.itsm.incident:
    state: new
    description: "Too many attempted user creations on a single host ({{ counter }} today)"
    short_description: "User Creation Violation"
    caller: admin
    urgency: "medium"
    impact: "high"
    other:
      u_operating_system: "{{ os | default(omit) }}"
      u_ip_address: "{{ ip_addr | default(omit) }}"
      u_vm_name: "{{ inventory_hostname | default(omit) }}"
  register: new_incident
  delegate_to: localhost
  when: counter|int >=4

- name: Display incident number
  ansible.builtin.debug:
    var: new_incident.record.number
