---

- name: RHV MEM increase
  ansible.builtin.include_tasks: rhv_vm_increase.yml
  when:
    - shadowman_mem == "increase"
    - shadowman_provision_hypervisor == "RHV"

- name: RHV MEM decrease
  ansible.builtin.include_tasks: rhv_vm_decrease.yml
  when:
    - shadowman_mem == "decrease"
    - shadowman_provision_hypervisor == "RHV"

- name: RHV MEM restore
  ansible.builtin.include_tasks: rhv_vm_restore.yml
  when:
    - shadowman_mem == "restore"
    - shadowman_provision_hypervisor == "RHV"

- name: VMWare MEM increase
  ansible.builtin.include_tasks: vmware_vm_increase.yml
  when:
    - shadowman_mem == "increase"
    - shadowman_provision_hypervisor == "VMWare"

- name: VMWare MEM decrease
  ansible.builtin.include_tasks: vmware_vm_decrease.yml
  when:
    - shadowman_mem == "decrease"
    - shadowman_provision_hypervisor == "VMWare"

- name: VMWare MEM restore
  ansible.builtin.include_tasks: vmware_vm_restore.yml
  when:
    - shadowman_mem == "restore"
    - shadowman_provision_hypervisor == "VMWare"
